export VERSION="@TESTCOCOON_VERSION_MAJOR@.@TESTCOCOON_VERSION_MINOR@.@TESTCOCOON_VERSION_PATCH@"
export VERSION_TAG="TESTCOCOON_@TESTCOCOON_VERSION_MAJOR@_@TESTCOCOON_VERSION_MINOR@_@TESTCOCOON_VERSION_PATCH@"
