#ifndef _CODECLINIC_VERSION_H_
#define _CODECLINIC_VERSION_H_

#define TESTCOCOON_VERSION ( ( @TESTCOCOON_VERSION_MAJOR@ << 16 ) | ( @TESTCOCOON_VERSION_MINOR@ << 8 )  | ( @TESTCOCOON_VERSION_PATCH@ ) )

#define TESTCOCOON_VERSION_QSTRING (QString::number((TESTCOCOON_VERSION>>16)&0xFF)+QString(".")+QString::number((TESTCOCOON_VERSION>>8)&0xFF)+QString(".")+QString::number(TESTCOCOON_VERSION&0xFF))
#endif
