
SET(TESTCOCOON_VERSION_MAJOR 1)
SET(TESTCOCOON_VERSION_MINOR 6)
SET(TESTCOCOON_VERSION_PATCH 10)
SET(TESTCOCOON_VERSION_DOT ${TESTCOCOON_VERSION_MAJOR}.${TESTCOCOON_VERSION_MINOR}.${TESTCOCOON_VERSION_PATCH})
SET(TESTCOCOON_VERSION_UNDERSCORE ${TESTCOCOON_VERSION_MAJOR}_${TESTCOCOON_VERSION_MINOR}_${TESTCOCOON_VERSION_PATCH})


